function retval = plotClassificationData (data, colors)  
  for i = 1 : 4
    scatter3(...
      data(i,:,1),...
      data(i,:,2),...
      data(i,:,3), colors(i));       
    hold on;
  endfor
  xlabel('wartosc maksymalna');
  ylabel('entropia');
  zlabel('nachylenie autokorelacji');
  legend ({"mul",...
    "antropogeniczy piasek i mul",...
    "piasek drobnoziarnisty",...
    "piasek gruboziarnisty"});
  legend show;
  title ("Rozklad dla paraemtrow: entropia, wartosc maksymalna oraz nacyhlenie autokorelacji");
  view(-100,30)
endfunction
