function retval = saveClassificationResultsToFile (classification_result)
  fileID = fopen(['results-' num2str(now) '.txt'],'w');
  x = classification_result(1,:);
  s = ['Rezultat klasyfikacji dna pierwszego:\n'...
       'Poprawnie sklasyfikowane ' num2str(size(x(x==1))(2))...
       '\n Zklasyfikowane jako dno drugie ' num2str(size(x(x==2))(2))...
       '\n Zklasyfikowane jako dno trzecie ' num2str(size(x(x==3))(2))...
       '\n Zklasyfikowane jako dno czwarte ' num2str(size(x(x==4))(2))...
       '\n Poprawnosc ' num2str((size(x(x==1))/300)(2)) '\n'];
  fprintf(fileID, s);

  x = classification_result(2,:);
  s = ['Rezultat klasyfikacji dna drugiego:\n'...
       'Poprawnie sklasyfikowane ' num2str(size(x(x==2))(2))...
       '\n Zklasyfikowane jako dno pierwsze ' num2str(size(x(x==1))(2))...
       '\n Zklasyfikowane jako dno trzecie ' num2str(size(x(x==3))(2))...
       '\n Zklasyfikowane jako dno czwarte ' num2str(size(x(x==4))(2))...
       '\n Poprawnosc ' num2str((size(x(x==2))/300)(2)) '\n'];
  fprintf(fileID, s);
       
  x = classification_result(3,:);
  s = ['Rezultat klasyfikacji dna trzeciego:\n'...
       'Poprawnie sklasyfikowane ' num2str(size(x(x==3))(2))...
       '\n Zklasyfikowane jako dno pierwsze ' num2str(size(x(x==1))(2))...
       '\n Zklasyfikowane jako dno drugie ' num2str(size(x(x==2))(2))...
       '\n Zklasyfikowane jako dno czwarte ' num2str(size(x(x==4))(2))...
       '\n Poprawnosc ' num2str((size(x(x==3))/300)(2)) '\n'];
  fprintf(fileID, s);

  x = classification_result(4,:);
  s = ['Rezultat klasyfikacji dna czwartego:\n'...
       'Poprawnie sklasyfikowane ' num2str(size(x(x==4))(2))...
       '\n Zklasyfikowane jako dno pierwsze ' num2str(size(x(x==1))(2))...
       '\n Zklasyfikowane jako dno drugie ' num2str(size(x(x==2))(2))...
       '\n Zklasyfikowane jako dno czwarte ' num2str(size(x(x==3))(2))...
       '\n Poprawnosc ' num2str((size(x(x==4))/300)(2)) '\n'];
  fprintf(fileID, s);

  fclose(fileID);

endfunction